_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 1300
log_every_n_steps: 1

# set to gpu for gpu training (if devices > 1, set ddp_find_unused_parameters_false: true)
accelerator: cpu
devices: 1
num_nodes: 1
