# Simple install with
# mamba env create -f environment.yml
name: myria3d
channels:
  - pytorch
  - nvidia
  - pyg
  - comet_ml
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  # --------- Deep Learning --------- #
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.16
  - conda-forge::lightning=2.0
  - conda-forge::torchmetrics=0.11
  - pyg::pyg=2.4
  - pyg::pytorch-cluster
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  # Troubleshooting: if libcusparse.so.11. errors occur, run
  # export LD_LIBRARY_PATH="/home/${USER}/miniconda/envs/lib:$LD_LIBRARY_PATH"
  # ou
  # export LD_LIBRARY_PATH="/home/${USER}/anaconda3/envs/lib:$LD_LIBRARY_PATH"
  # see https://github.com/pyg-team/pytorch_geometric/issues/2040#issuecomment-766610625
  # --------- data formats --------- #
  - numpy
  - h5py
  # --------- geo --------- #
  - pdal
  - python-pdal
  - pyproj
    # --------- Visualization --------- #
  - pandas
  - matplotlib
  # --------- loggers --------- #
  - comet_ml::comet_ml=3.35
  - conda-forge::urllib3<2  # To solve for https://github.com/GeneralMills/pytrends/issues/591
    # --------- Visualization --------- #
  - pandas
  - matplotlib
  - seaborn # used in some callbacks
  # --------- linters --------- #
  - pre-commit # hooks for applying linters on commit
  - black # code formatting
  - isort # import sorting
  - flake8 # code analysis
  # --------- tests --------- #
  - pytest==7.1.*
  - coverage==6.3.*
  - pytest-cov==3.0.*
  # --------- others --------- #
  - python-dotenv # loading env variables from .env file
  - rich # beautiful text formatting in terminal
  - sh # for running bash commands in some tests
  - pudb # debugger
    # # --------- Documentation --------- #
  - sphinx==4.5.*
  - recommonmark==0.7.*
  - sphinx_rtd_theme==1.0.*
  - docutils==0.17
  - rstcheck==3.3.*  # RST Linter
  - pip:
    - hydra-core==1.1.*
    - hydra-colorlog==1.1.*
    # --------- Documentation --------- #
    - myst_parser==0.17.*
    - sphinxnotes-mock==1.0.0b0  # still a beta
    - sphinx_paramlinks==0.5.*