# Do not scale positions to keep meter-space for neural network parameters

NullifyLowestZ:
  _target_: myria3d.pctl.transforms.transforms.NullifyLowestZ

NormalizePos:
  _target_: myria3d.pctl.transforms.transforms.NormalizePos
  subtile_width: "${datamodule.subtile_width}"

StandardizeRGBAndIntensity:
  _target_: myria3d.pctl.transforms.transforms.StandardizeRGBAndIntensity

AblationOfAllColors:
  _target_: myria3d.pctl.transforms.transforms.AblationOfAllColors
