# Workflow name
name: "Documentation Build"

# Event that must trigger the workflow
on: push         # <- trigger when we call push
    # branches:
    #   - main  # <- but only on main branch

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    # Use bash instead of sh for conda activation
    defaults:
      run:
        shell: bash -l {0}
    # Task to do when launching the workflow
    steps:

      # 1. First get the repository source

      - name: "Checkout"
        uses: actions/checkout@v2

      # 2. Sphinx part : install tool and dependencies
      # See https://github.com/conda-incubator/setup-miniconda#caching-environments

      - name: Setup a conda-incubator with an empty conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
            python-version: 3.9.12
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            # For caching to work:
            use-only-tar-bz2: true
            # Environment to create and activate for next steps
            activate-environment: myria3d_pyg2_1_0

      # Cache the conda environment
      # See https://github.com/conda-incubator/setup-miniconda#caching-environments
      # UNCOMMENT TO REACTIVATE CACHING ONCE CONDA BUILDS ARE AVAILABLE FOR PYG >=2.1
      # - name: Get Date
      #   id: get-date
      #   run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
      #   shell: bash

      # - name: Cache conda environment
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.CONDA }}/envs
      #     key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('setup_env/requirements.yml') }}-${{ hashFiles('setup_env/requirements.txt') }}
      #   env:
      #     # Increase this value to reset cache if etc/example-environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   id: cache

      - name: Update environment if there was no cached env.
        run: bash -c "source ./setup_env/setup_env.sh"
        # if: steps.cache.outputs.cache-hit != 'true'

      - name: List installed packages
        run: mamba list

      - name: "Build Sphinx Doc"
        working-directory: ./docs/
        run: make html

      # 3. DÃ©ploiement sur les Github Pages
      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages     # <- Branch where generated doc files will be commited
          FOLDER: docs/build/html/  # <- Dir where .nojekyll is created and from which to deploy github pages.
