_convert_: all  # For omegaconf struct to be converted to python dictionnaries
# classification_preprocessing_dict = {source_class_code_int: target_class_code_int},
classification_preprocessing_dict: {59: 6, 50: 1}
# classification_dict = {code_int: name_str, ...} and MUST be sorted (increasing order).
classification_dict: {1: "unclassified", 2: "ground", 6: "building"}

# Input and output dims of neural net are dataset dependant:
d_in: 12
num_classes: 3

# loading functions for data object prepared via lidar_multiclass/datamodule/data.py
load_las_func:
  _target_: functools.partial
  _args_:
    - "${get_method:lidar_multiclass.datamodules.data.FrenchLidarDataLogic.load_las}"