# Characteristics of datasets obtained from SwissTopo Data
# In particular: from cmbining SwissSURFACE3D and SwissIMAGE10cm

# classification_dict = {int: name, ...} and MUST be sorted (increasing order).
classification_dict: {1: "unclassified", 2: "ground", 3: "vegetation", 6: "building", 9: "water", 17: "bridge"}
# features_names to include. You must use names from LAS convention for standard channels.
# XYZ will also be included.
features_names:  
  - "intensity"
  - "return_num"
  - "num_returns"
  - "red"
  - "green"
  - "blue"
  - "composite"
  # INPUT specific parameters: change to apply on data with different scale.
  # Largest values for intensity, colors (if applicable), and return number
colors_normalization_max_value: 256  # usually 256*256 or 256 (sometimes 1?)
return_num_normalization_max_value: 7  # usually constant across datasets